version = 1

[[analyzers]]
name = "python"
enabled = true
test_patterns = ["classquiz/tests/**", "test_*.py"]

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

