name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: input
    attributes:
      label: Which component is affected?
      description: Which component/part of ClassQuiz is affected by the bug? The editor? The admin-screen if a game is running?
      validations:
        required: true
  - type: dropdown
    attributes:
      label: Did the issue occur at ClassQuiz.de, or on a self-hosted instance?
      options:
        - On ClassQuiz.de
        - On a self-hosted instance
    validation:
      required: true
  - type: markdown
    attributes:
      value: How can the issue be reproduced?
      validation:
        required: true
  - type: markdown
    attributes:
      value: Describe the bug (with screenshots if possible)
      validation:
        required: true
  - type: dropdown
    attributes:
      label: Device
      options:
        - Desktop
        - Laptop/Notebook
        - Smartphone
        - Tablet
        - Smartwatch
        - Fridge/Toaster
  - type: input
    attributes:
      label: Operating System
      placeholder: Windows, Linux, iOS, etc
  - type: input
    attributes: Browser
    placeholder: Chrome, Safari, Firefox, etc
  - type: markdown
    attributes:
      value: Additional
      validation:
        required: true
