# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "[CI] Frontend / Lint"

on:
  push:
    branches: [ master ]
    paths:
      - "frontend/**"
  pull_request:

jobs:
  frontend_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
          working-directory: ./frontend

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          pnpm install

      - name: Lint
        working-directory: ./frontend
        run: |
          pnpm run lint
